Traceback (most recent call last):
  File "/home/esrf/ljegou/.local/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/esrf/ljegou/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/esrf/ljegou/.local/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/esrf/ljegou/.local/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/esrf/ljegou/.local/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/esrf/ljegou/.local/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/esrf/ljegou/.local/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
if combine_refined:
    tensor_map_combined.to_h5(os.path.join(ds.analysispath, f'{ds.sample}_{ds.dset}_refined_tmap_combined.h5'))
    tensor_map_combined.to_paraview(os.path.join(ds.analysispath, f'{ds.sample}_{ds.dset}_refined_tmap_combined.h5'))
else:
    tensor_map_combined.to_h5(os.path.join(ds.analysispath, f'{ds.sample}_{ds.dset}_tmap_combined.h5'))
    tensor_map_combined.to_paraview(os.path.join(ds.analysispath, f'{ds.sample}_{ds.dset}_tmap_combined.h5'))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
Cell [0;32mIn[12], line 2[0m
[1;32m      1[0m [38;5;28;01mif[39;00m combine_refined:
[0;32m----> 2[0m     [43mtensor_map_combined[49m[38;5;241;43m.[39;49m[43mto_h5[49m[43m([49m[43mos[49m[38;5;241;43m.[39;49m[43mpath[49m[38;5;241;43m.[39;49m[43mjoin[49m[43m([49m[43mds[49m[38;5;241;43m.[39;49m[43manalysispath[49m[43m,[49m[43m [49m[38;5;124;43mf[39;49m[38;5;124;43m'[39;49m[38;5;132;43;01m{[39;49;00m[43mds[49m[38;5;241;43m.[39;49m[43msample[49m[38;5;132;43;01m}[39;49;00m[38;5;124;43m_[39;49m[38;5;132;43;01m{[39;49;00m[43mds[49m[38;5;241;43m.[39;49m[43mdset[49m[38;5;132;43;01m}[39;49;00m[38;5;124;43m_refined_tmap_combined.h5[39;49m[38;5;124;43m'[39;49m[43m)[49m[43m)[49m
[1;32m      3[0m     tensor_map_combined[38;5;241m.[39mto_paraview(os[38;5;241m.[39mpath[38;5;241m.[39mjoin(ds[38;5;241m.[39manalysispath, [38;5;124mf[39m[38;5;124m'[39m[38;5;132;01m{[39;00mds[38;5;241m.[39msample[38;5;132;01m}[39;00m[38;5;124m_[39m[38;5;132;01m{[39;00mds[38;5;241m.[39mdset[38;5;132;01m}[39;00m[38;5;124m_refined_tmap_combined.h5[39m[38;5;124m'[39m))
[1;32m      4[0m [38;5;28;01melse[39;00m:

File [0;32m~/Code/Tutorial/SCRIPTS/ImageD11/ImageD11/sinograms/tensor_map.py:1012[0m, in [0;36mTensorMap.to_h5[0;34m(self, h5file, h5group)[0m
[1;32m   1010[0m phase_group [38;5;241m=[39m parent_group[38;5;241m.[39mrequire_group([38;5;124m'[39m[38;5;124mphases[39m[38;5;124m'[39m)
[1;32m   1011[0m [38;5;28;01mfor[39;00m phase_id [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mphases[38;5;241m.[39mkeys():
[0;32m-> 1012[0m     [43mphase_group[49m[43m[[49m[38;5;28;43mstr[39;49m[43m([49m[43mphase_id[49m[43m)[49m[43m][49m [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mphases[phase_id][38;5;241m.[39mtostring()
[1;32m   1013[0m     [38;5;66;03m# store the phase name as an attribute[39;00m
[1;32m   1014[0m     phase_group[[38;5;28mstr[39m(phase_id)][38;5;241m.[39mattrs[[38;5;124m'[39m[38;5;124mphase_name[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mphases[phase_id][38;5;241m.[39mname

File [0;32m~/.conda/envs/diffraction/lib/python3.9/site-packages/h5py/_hl/group.py:487[0m, in [0;36mGroup.__setitem__[0;34m(self, name, obj)[0m
[1;32m    485[0m [38;5;28;01melse[39;00m:
[1;32m    486[0m     ds [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mcreate_dataset([38;5;28;01mNone[39;00m, data[38;5;241m=[39mobj)
[0;32m--> 487[0m     [43mh5o[49m[38;5;241;43m.[39;49m[43mlink[49m[43m([49m[43mds[49m[38;5;241;43m.[39;49m[43mid[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mid[49m[43m,[49m[43m [49m[43mname[49m[43m,[49m[43m [49m[43mlcpl[49m[38;5;241;43m=[39;49m[43mlcpl[49m[43m)[49m

File [0;32mh5py/_objects.pyx:56[0m, in [0;36mh5py._objects.with_phil.wrapper[0;34m()[0m

File [0;32mh5py/_objects.pyx:57[0m, in [0;36mh5py._objects.with_phil.wrapper[0;34m()[0m

File [0;32mh5py/h5o.pyx:269[0m, in [0;36mh5py.h5o.link[0;34m()[0m

[0;31mOSError[0m: Unable to create link (name already exists)

